Upgrade to Decidim v0.23
CodiTramuntana/decidim-erc-app pull request #57
Opened 2021-04-19 13:33 UTC by LauraJaimeC

Changelog: https://github.com/decidim/decidim/blob/release/0.23-stable/CHANGELOG.md

- Update Decidim to v0.23
- Update Ruby to 2.7.2
- Changes in geocoder configuration

!!!!!
This PR depends of https://github.com/CodiTramuntana/decidim-erc-crm_authenticable/pull/17
It is necessary to change the Gemfile when this PR will merge.

2021-04-23 09:24 UTC, tramuntanal requested changes
I think it's better to use our fork for this version @LauraJaimeC 

Also, we must remember this from the changelog:
> Debates and Comments have been added to the global search and need to be indexed, otherwise all previous content won't be available as search results. You should run this in a Rails console at your server or create a migration to do it.
>
> Please be aware that it could take a while if your database has a lot of content.
> ```
>  Decidim::Comments::Comment.find_each(&:try_update_index_for_search_resource)
>  Decidim::Debates::Debate.find_each(&:try_update_index_for_search_resource)
> ```

2021-04-23 09:24 UTC, tramuntanal commented on Gemfile
> +DECIDIM_VERSION = { git: 'https://github.com/decidim/decidim.git', branch: 'release/0.23-stable' }
We have many fixes for 0.23 in our fork, maybe it will be better to use that repo, same branch

2021-04-26 06:19 UTC, LauraJaimeC commented
> I think it's better to use our fork for this version @LauraJaimeC
> 
> Also, we must remember this from the changelog:
> 
> > Debates and Comments have been added to the global search and need to be indexed, otherwise all previous content won't be available as search results. You should run this in a Rails console at your server or create a migration to do it.
> > Please be aware that it could take a while if your database has a lot of content.
> > ```
> >  Decidim::Comments::Comment.find_each(&:try_update_index_for_search_resource)
> >  Decidim::Debates::Debate.find_each(&:try_update_index_for_search_resource)
> > ```

This content of changelog it's already in upgrades doc

2021-04-26 14:15 UTC, tramuntanal requested changes
It seems that the schema.rb has not been updated

2021-04-27 06:52 UTC, LauraJaimeC commented
> It seems that the schema.rb has not been updated

I have tried to update and it won't let me. I've deleted the schema and I run migrates and it doesn't change.

2021-04-28 07:45 UTC, tramuntanal approved these changes

2021-04-28 10:44 UTC, merged